### ISSUE TITLE
Memory leak with full rt.jar, lazy-methods

### ISSUE THREAD

**Issue by reuk** [diffblue/cbmc#877]
I'm not sure if this is the minimal test case, but I think it's pretty close. On f5aa612 (tip of test-gen-support), the following test case results in a memory leak.

```java
package Iterator;

import java.util.Iterator;
import org.cprover.CProver;

class MyIterator implements Iterator {
  private int index = 0;

  public boolean hasNext() {
    return index < 5;
  }

  public Object next() {
    index += 1;
    return null;
  }
}

public class Loop_foreach_Pass {
  public static void main(String[] args) {
    int iterations = 0;

    Iterator iterator = new MyIterator();
    while (iterator.hasNext()) {
      iterator.next();
      iterations += 1;
    }

    assert iterations == 5;
  }
}
```

command-line:
```
cbmc Iterator/Loop_foreach_Pass.class --lazy-methods --classpath ../build/linux-x86_64-normal-server-release/images/j2re-image/lib/rt.jar:. --unwind 8
```

truncated output:
```
** 0 of 151 failed (1 iteration)
VERIFICATION SUCCESSFUL

=================================================================
==11804==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 2560 byte(s) in 20 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0x78dced in irept::detach() /home/reuben/development/cbmc/src/util/irep.cpp:113:10

Indirect leak of 2160 byte(s) in 45 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0x79a216 in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<dstringt const, irept> > >::allocate(unsigned long, void const*) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/ext/new_allocator.h:104:27
    #2 0x79a216 in std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<dstringt const, irept> > > >::allocate(std::allocator<std::_Rb_tree_node<std::pair<dstringt const, irept> > >&, unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/alloc_traits.h:491
    #3 0x79a216 in std::_Rb_tree<dstringt, std::pair<dstringt const, irept>, std::_Select1st<std::pair<dstringt const, irept> >, std::less<dstringt>, std::allocator<std::pair<dstringt const, irept> > >::_M_get_node() /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_tree.h:491

Indirect leak of 1664 byte(s) in 13 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0x78dda0 in irept::detach() /home/reuben/development/cbmc/src/util/irep.cpp:104:10
    #2 0xb1aea2 in java_bytecode_convert_classt::operator()(java_bytecode_parse_treet const&) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_convert_class.cpp:49:7
    #3 0xb16726 in java_bytecode_convert_class(java_bytecode_parse_treet const&, symbol_tablet&, message_handlert&, unsigned long, std::map<dstringt, std::pair<symbolt const*, java_bytecode_parse_treet::methodt const*>, std::less<dstringt>, std::allocator<std::pair<dstringt const, std::pair<symbolt const*, java_bytecode_parse_treet::methodt const*> > > >&, lazy_methods_modet, bool) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_convert_class.cpp:499:5
    #4 0xa136d8 in java_bytecode_languaget::typecheck(symbol_tablet&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_language.cpp:526:8
    #5 0x19b8325 in language_filest::typecheck(symbol_tablet&) /home/reuben/development/cbmc/src/util/language_file.cpp:223:10
    #6 0x152f0df in language_uit::typecheck() /home/reuben/development/cbmc/src/langapi/language_ui.cpp:159:6

Indirect leak of 768 byte(s) in 16 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0x79a216 in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<dstringt const, irept> > >::allocate(unsigned long, void const*) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/ext/new_allocator.h:104:27
    #2 0x79a216 in std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<dstringt const, irept> > > >::allocate(std::allocator<std::_Rb_tree_node<std::pair<dstringt const, irept> > >&, unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/alloc_traits.h:491
    #3 0x79a216 in std::_Rb_tree<dstringt, std::pair<dstringt const, irept>, std::_Select1st<std::pair<dstringt const, irept> >, std::less<dstringt>, std::allocator<std::pair<dstringt const, irept> > >::_M_get_node() /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_tree.h:491
    #4 0x794a76 in std::map<dstringt, irept, std::less<dstringt>, std::allocator<std::pair<dstringt const, irept> > >::map(std::map<dstringt, irept, std::less<dstringt>, std::allocator<std::pair<dstringt const, irept> > > const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_map.h:186:9
    #5 0x794a76 in irept::dt::dt(irept::dt const&) /home/reuben/development/cbmc/src/util/./irep.h:260

Indirect leak of 640 byte(s) in 5 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0x78dda0 in irept::detach() /home/reuben/development/cbmc/src/util/irep.cpp:104:10

Indirect leak of 640 byte(s) in 5 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0x78dda0 in irept::detach() /home/reuben/development/cbmc/src/util/irep.cpp:104:10
    #2 0xb0f1b1 in java_bytecode_convert_classt::convert(java_bytecode_parse_treet::classt const&) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_convert_class.cpp:179:5
    #3 0xb1aea2 in java_bytecode_convert_classt::operator()(java_bytecode_parse_treet const&) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_convert_class.cpp:49:7
    #4 0xb16726 in java_bytecode_convert_class(java_bytecode_parse_treet const&, symbol_tablet&, message_handlert&, unsigned long, std::map<dstringt, std::pair<symbolt const*, java_bytecode_parse_treet::methodt const*>, std::less<dstringt>, std::allocator<std::pair<dstringt const, std::pair<symbolt const*, java_bytecode_parse_treet::methodt const*> > > >&, lazy_methods_modet, bool) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_convert_class.cpp:499:5
    #5 0xa136d8 in java_bytecode_languaget::typecheck(symbol_tablet&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_language.cpp:526:8
    #6 0x19b8325 in language_filest::typecheck(symbol_tablet&) /home/reuben/development/cbmc/src/util/language_file.cpp:223:10
    #7 0x152f0df in language_uit::typecheck() /home/reuben/development/cbmc/src/langapi/language_ui.cpp:159:6

Indirect leak of 384 byte(s) in 3 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0x78dda0 in irept::detach() /home/reuben/development/cbmc/src/util/irep.cpp:104:10
    #2 0xb0eac7 in java_bytecode_convert_classt::convert(java_bytecode_parse_treet::classt const&) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_convert_class.cpp:158:5
    #3 0xb1aea2 in java_bytecode_convert_classt::operator()(java_bytecode_parse_treet const&) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_convert_class.cpp:49:7
    #4 0xb16726 in java_bytecode_convert_class(java_bytecode_parse_treet const&, symbol_tablet&, message_handlert&, unsigned long, std::map<dstringt, std::pair<symbolt const*, java_bytecode_parse_treet::methodt const*>, std::less<dstringt>, std::allocator<std::pair<dstringt const, std::pair<symbolt const*, java_bytecode_parse_treet::methodt const*> > > >&, lazy_methods_modet, bool) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_convert_class.cpp:499:5
    #5 0xa136d8 in java_bytecode_languaget::typecheck(symbol_tablet&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_language.cpp:526:8
    #6 0x19b8325 in language_filest::typecheck(symbol_tablet&) /home/reuben/development/cbmc/src/util/language_file.cpp:223:10
    #7 0x152f0df in language_uit::typecheck() /home/reuben/development/cbmc/src/langapi/language_ui.cpp:159:6

Indirect leak of 384 byte(s) in 3 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0x78dda0 in irept::detach() /home/reuben/development/cbmc/src/util/irep.cpp:104:10
    #2 0x7c6d23 in bitvector_typet::set_width(unsigned long) /home/reuben/development/cbmc/src/util/./std_types.h:1045:5
    #3 0x7c6d23 in bitvector_typet::bitvector_typet(dstringt const&, unsigned long) /home/reuben/development/cbmc/src/util/./std_types.h:1035

Indirect leak of 288 byte(s) in 6 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0x79a216 in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<dstringt const, irept> > >::allocate(unsigned long, void const*) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/ext/new_allocator.h:104:27
    #2 0x79a216 in std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<dstringt const, irept> > > >::allocate(std::allocator<std::_Rb_tree_node<std::pair<dstringt const, irept> > >&, unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/alloc_traits.h:491
    #3 0x79a216 in std::_Rb_tree<dstringt, std::pair<dstringt const, irept>, std::_Select1st<std::pair<dstringt const, irept> >, std::less<dstringt>, std::allocator<std::pair<dstringt const, irept> > >::_M_get_node() /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_tree.h:491
    #4 0x794ab5 in std::map<dstringt, irept, std::less<dstringt>, std::allocator<std::pair<dstringt const, irept> > >::map(std::map<dstringt, irept, std::less<dstringt>, std::allocator<std::pair<dstringt const, irept> > > const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_map.h:186:9
    #5 0x794ab5 in irept::dt::dt(irept::dt const&) /home/reuben/development/cbmc/src/util/./irep.h:260

Indirect leak of 256 byte(s) in 2 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0x78dda0 in irept::detach() /home/reuben/development/cbmc/src/util/irep.cpp:104:10
    #2 0xbae5a3 in java_bytecode_parsert::rmethod_attribute(java_bytecode_parse_treet::methodt&) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_parser.cpp:995:5
    #3 0xbb692a in java_bytecode_parsert::rmethod(java_bytecode_parse_treet::classt&) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_parser.cpp:1567:5

Indirect leak of 256 byte(s) in 2 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0x78dda0 in irept::detach() /home/reuben/development/cbmc/src/util/irep.cpp:104:10
    #2 0x78ddb4 in irept::detach() /home/reuben/development/cbmc/src/util/irep.cpp:104:14

Indirect leak of 256 byte(s) in 2 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0x78dda0 in irept::detach() /home/reuben/development/cbmc/src/util/irep.cpp:104:10
    #2 0xb18770 in class_typet::class_typet() /home/reuben/development/cbmc/src/java_bytecode/../util/std_types.h:338:5

Indirect leak of 256 byte(s) in 2 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0x78dda0 in irept::detach() /home/reuben/development/cbmc/src/util/irep.cpp:104:10
    #2 0x13e8797 in ssa_exprt::ssa_exprt(exprt const&) /home/reuben/development/cbmc/src/goto-symex/../util/ssa_expr.h:32:5

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0x78dda0 in irept::detach() /home/reuben/development/cbmc/src/util/irep.cpp:104:10
    #2 0x142f27e in ssa_exprt::set_level_2(unsigned int) /home/reuben/development/cbmc/src/goto-symex/../util/ssa_expr.h:96:5

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0x78dda0 in irept::detach() /home/reuben/development/cbmc/src/util/irep.cpp:104:10
    #2 0x136ec02 in set_class_identifier(struct_exprt&, namespacet const&, symbol_typet const&) /home/reuben/development/cbmc/src/goto-programs/builtin_functions.cpp:677:5
    #3 0x136f7a3 in goto_convertt::do_java_new(exprt const&, side_effect_exprt const&, goto_programt&) /home/reuben/development/cbmc/src/goto-programs/builtin_functions.cpp:741:3
    #4 0x118f7aa in goto_convertt::convert_assign(code_assignt const&, goto_programt&) /home/reuben/development/cbmc/src/goto-programs/goto_convert.cpp:966:5
    #5 0x118207f in goto_convertt::convert(codet const&, goto_programt&) /home/reuben/development/cbmc/src/goto-programs/goto_convert.cpp:599:5
    #6 0x118ae09 in goto_convertt::convert_block(code_blockt const&, goto_programt&) /home/reuben/development/cbmc/src/goto-programs/goto_convert.cpp:742:5
    #7 0x1181ce5 in goto_convertt::convert(codet const&, goto_programt&) /home/reuben/development/cbmc/src/goto-programs/goto_convert.cpp:591:5
    #8 0x1187ed7 in goto_convertt::convert_label(code_labelt const&, goto_programt&) /home/reuben/development/cbmc/src/goto-programs/goto_convert.cpp:448:5
    #9 0x1182508 in goto_convertt::convert(codet const&, goto_programt&) /home/reuben/development/cbmc/src/goto-programs/goto_convert.cpp:609:5
    #10 0x118ae09 in goto_convertt::convert_block(code_blockt const&, goto_programt&) /home/reuben/development/cbmc/src/goto-programs/goto_convert.cpp:742:5
    #11 0x1181ce5 in goto_convertt::convert(codet const&, goto_programt&) /home/reuben/development/cbmc/src/goto-programs/goto_convert.cpp:591:5
    #12 0x1180321 in goto_convertt::goto_convert_rec(codet const&, goto_programt&) /home/reuben/development/cbmc/src/goto-programs/goto_convert.cpp:380:3
    #13 0x11dba96 in goto_convert_functionst::convert_function(dstringt const&) /home/reuben/development/cbmc/src/goto-programs/goto_convert_functions.cpp:256:3
    #14 0x11daa67 in goto_convert_functionst::goto_convert() /home/reuben/development/cbmc/src/goto-programs/goto_convert_functions.cpp:91:5
    #15 0x11deedc in goto_convert(symbol_tablet&, goto_functionst&, message_handlert&) /home/reuben/development/cbmc/src/goto-programs/goto_convert_functions.cpp:338:5
    #16 0x9a7d64 in cbmc_parse_optionst::get_goto_program(optionst const&, bmct&, goto_functionst&) /home/reuben/development/cbmc/src/cbmc/cbmc_parse_options.cpp:744:5
    #17 0x9a08d5 in cbmc_parse_optionst::doit() /home/reuben/development/cbmc/src/cbmc/cbmc_parse_options.cpp:543:5
    #18 0x9935f9 in main /home/reuben/development/cbmc/src/cbmc/cbmc_main.cpp:53:11
    #19 0x7f5a1d27482f in __libc_start_main /build/glibc-9tT8Do/glibc-2.23/csu/../csu/libc-start.c:291

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0x78dda0 in irept::detach() /home/reuben/development/cbmc/src/util/irep.cpp:104:10
    #2 0xb9e7de in java_bytecode_parsert::rClassFile() /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_parser.cpp:325:5
    #3 0xb9d2c7 in java_bytecode_parsert::parse() /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_parser.cpp:219:5

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0x78dda0 in irept::detach() /home/reuben/development/cbmc/src/util/irep.cpp:104:10
    #2 0x11572e4 in zero_initializert::zero_initializer_rec(typet const&, source_locationt const&) /home/reuben/development/cbmc/src/linking/zero_initializer.cpp:88:18
    #3 0x11586ce in zero_initializert::zero_initializer_rec(typet const&, source_locationt const&) /home/reuben/development/cbmc/src/linking/zero_initializer.cpp:224:11
    #4 0x1159442 in zero_initializert::zero_initializer_rec(typet const&, source_locationt const&) /home/reuben/development/cbmc/src/linking/zero_initializer.cpp:281:18
    #5 0x11586ce in zero_initializert::zero_initializer_rec(typet const&, source_locationt const&) /home/reuben/development/cbmc/src/linking/zero_initializer.cpp:224:11
    #6 0x1159442 in zero_initializert::zero_initializer_rec(typet const&, source_locationt const&) /home/reuben/development/cbmc/src/linking/zero_initializer.cpp:281:18
    #7 0x115f592 in zero_initializert::operator()(typet const&, source_locationt const&) /home/reuben/development/cbmc/src/linking/zero_initializer.cpp:38:12
    #8 0x136f6f7 in goto_convertt::do_java_new(exprt const&, side_effect_exprt const&, goto_programt&) /home/reuben/development/cbmc/src/goto-programs/builtin_functions.cpp:740:5
    #9 0x118f7aa in goto_convertt::convert_assign(code_assignt const&, goto_programt&) /home/reuben/development/cbmc/src/goto-programs/goto_convert.cpp:966:5
    #10 0x118207f in goto_convertt::convert(codet const&, goto_programt&) /home/reuben/development/cbmc/src/goto-programs/goto_convert.cpp:599:5
    #11 0x118ae09 in goto_convertt::convert_block(code_blockt const&, goto_programt&) /home/reuben/development/cbmc/src/goto-programs/goto_convert.cpp:742:5
    #12 0x1181ce5 in goto_convertt::convert(codet const&, goto_programt&) /home/reuben/development/cbmc/src/goto-programs/goto_convert.cpp:591:5
    #13 0x1187ed7 in goto_convertt::convert_label(code_labelt const&, goto_programt&) /home/reuben/development/cbmc/src/goto-programs/goto_convert.cpp:448:5
    #14 0x1182508 in goto_convertt::convert(codet const&, goto_programt&) /home/reuben/development/cbmc/src/goto-programs/goto_convert.cpp:609:5
    #15 0x118ae09 in goto_convertt::convert_block(code_blockt const&, goto_programt&) /home/reuben/development/cbmc/src/goto-programs/goto_convert.cpp:742:5
    #16 0x1181ce5 in goto_convertt::convert(codet const&, goto_programt&) /home/reuben/development/cbmc/src/goto-programs/goto_convert.cpp:591:5
    #17 0x1180321 in goto_convertt::goto_convert_rec(codet const&, goto_programt&) /home/reuben/development/cbmc/src/goto-programs/goto_convert.cpp:380:3
    #18 0x11dba96 in goto_convert_functionst::convert_function(dstringt const&) /home/reuben/development/cbmc/src/goto-programs/goto_convert_functions.cpp:256:3
    #19 0x11daa67 in goto_convert_functionst::goto_convert() /home/reuben/development/cbmc/src/goto-programs/goto_convert_functions.cpp:91:5
    #20 0x11deedc in goto_convert(symbol_tablet&, goto_functionst&, message_handlert&) /home/reuben/development/cbmc/src/goto-programs/goto_convert_functions.cpp:338:5
    #21 0x9a7d64 in cbmc_parse_optionst::get_goto_program(optionst const&, bmct&, goto_functionst&) /home/reuben/development/cbmc/src/cbmc/cbmc_parse_options.cpp:744:5
    #22 0x9a08d5 in cbmc_parse_optionst::doit() /home/reuben/development/cbmc/src/cbmc/cbmc_parse_options.cpp:543:5
    #23 0x9935f9 in main /home/reuben/development/cbmc/src/cbmc/cbmc_main.cpp:53:11
    #24 0x7f5a1d27482f in __libc_start_main /build/glibc-9tT8Do/glibc-2.23/csu/../csu/libc-start.c:291

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0x78dda0 in irept::detach() /home/reuben/development/cbmc/src/util/irep.cpp:104:10
    #2 0x1a900cb in _fini (/home/reuben/development/cbmc/src/cbmc/cbmc+0x1a900cb)

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0x78dda0 in irept::detach() /home/reuben/development/cbmc/src/util/irep.cpp:104:10
    #2 0x14a353f in goto_symext::symex_step(goto_functionst const&, goto_symex_statet&) /home/reuben/development/cbmc/src/goto-symex/symex_main.cpp:299:5
    #3 0x9eec8b in symex_bmct::symex_step(goto_functionst const&, goto_symex_statet&) /home/reuben/development/cbmc/src/cbmc/symex_bmc.cpp:84:3
    #4 0x14a22a4 in goto_symext::operator()(goto_symex_statet&, goto_functionst const&, goto_programt const&) /home/reuben/development/cbmc/src/goto-symex/symex_main.cpp:177:5
    #5 0x14a2b1e in goto_symext::operator()(goto_functionst const&, goto_programt const&) /home/reuben/development/cbmc/src/goto-symex/symex_main.cpp:210:3
    #6 0x14a2ec5 in goto_symext::operator()(goto_functionst const&) /home/reuben/development/cbmc/src/goto-symex/symex_main.cpp:235:3
    #7 0x9518a1 in bmct::run(goto_functionst const&) /home/reuben/development/cbmc/src/cbmc/bmc.cpp:451:5
    #8 0x9aee78 in cbmc_parse_optionst::do_bmc(bmct&, goto_functionst const&) /home/reuben/development/cbmc/src/cbmc/cbmc_parse_options.cpp:1048:10
    #9 0x1b30c0f in _fini (/home/reuben/development/cbmc/src/cbmc/cbmc+0x1b30c0f)

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0x78dda0 in irept::detach() /home/reuben/development/cbmc/src/util/irep.cpp:104:10
    #2 0xb0e364 in java_bytecode_convert_classt::convert(java_bytecode_parse_treet::classt const&) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_convert_class.cpp:121:5
    #3 0xb1aea2 in java_bytecode_convert_classt::operator()(java_bytecode_parse_treet const&) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_convert_class.cpp:49:7
    #4 0xb16726 in java_bytecode_convert_class(java_bytecode_parse_treet const&, symbol_tablet&, message_handlert&, unsigned long, std::map<dstringt, std::pair<symbolt const*, java_bytecode_parse_treet::methodt const*>, std::less<dstringt>, std::allocator<std::pair<dstringt const, std::pair<symbolt const*, java_bytecode_parse_treet::methodt const*> > > >&, lazy_methods_modet, bool) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_convert_class.cpp:499:5
    #5 0xa136d8 in java_bytecode_languaget::typecheck(symbol_tablet&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_language.cpp:526:8
    #6 0x19b8325 in language_filest::typecheck(symbol_tablet&) /home/reuben/development/cbmc/src/util/language_file.cpp:223:10
    #7 0x152f0df in language_uit::typecheck() /home/reuben/development/cbmc/src/langapi/language_ui.cpp:159:6

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0x78dda0 in irept::detach() /home/reuben/development/cbmc/src/util/irep.cpp:104:10
    #2 0xbb16db in source_locationt::set_line(unsigned int) /home/reuben/development/cbmc/src/java_bytecode/../util/source_location.h:99:5
    #3 0xbb16db in java_bytecode_parsert::rcode_attribute(java_bytecode_parse_treet::methodt&) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_parser.cpp:1125
    #4 0xbaf1bd in java_bytecode_parsert::rmethod_attribute(java_bytecode_parse_treet::methodt&) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_parser.cpp:1017:7
    #5 0xbb692a in java_bytecode_parsert::rmethod(java_bytecode_parse_treet::classt&) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_parser.cpp:1567:5

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0x78dda0 in irept::detach() /home/reuben/development/cbmc/src/util/irep.cpp:104:10
    #2 0x13e8757 in ssa_exprt::ssa_exprt(exprt const&) /home/reuben/development/cbmc/src/goto-symex/../util/ssa_expr.h:30:5

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0x78dda0 in irept::detach() /home/reuben/development/cbmc/src/util/irep.cpp:104:10
    #2 0xbb692a in java_bytecode_parsert::rmethod(java_bytecode_parse_treet::classt&) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_parser.cpp:1567:5

Indirect leak of 104 byte(s) in 6 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0x548eea in __gnu_cxx::new_allocator<irept>::allocate(unsigned long, void const*) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/ext/new_allocator.h:104:27
    #2 0x548eea in std::allocator_traits<std::allocator<irept> >::allocate(std::allocator<irept>&, unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/alloc_traits.h:491
    #3 0x548eea in std::_Vector_base<irept, std::allocator<irept> >::_M_allocate(unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_vector.h:170

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x5132c0 in operator new(unsigned long) (/home/reuben/development/cbmc/src/cbmc/cbmc+0x5132c0)
    #1 0xb1cefa in __gnu_cxx::new_allocator<class_typet::baset>::allocate(unsigned long, void const*) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/ext/new_allocator.h:104:27
    #2 0xb1cefa in std::allocator_traits<std::allocator<class_typet::baset> >::allocate(std::allocator<class_typet::baset>&, unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/alloc_traits.h:491
    #3 0xb1cefa in std::_Vector_base<class_typet::baset, std::allocator<class_typet::baset> >::_M_allocate(unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_vector.h:170
    #4 0xb0e703 in java_bytecode_convert_classt::convert(java_bytecode_parse_treet::classt const&) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_convert_class.cpp:134:5
    #5 0xb1aea2 in java_bytecode_convert_classt::operator()(java_bytecode_parse_treet const&) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_convert_class.cpp:49:7
    #6 0xb16726 in java_bytecode_convert_class(java_bytecode_parse_treet const&, symbol_tablet&, message_handlert&, unsigned long, std::map<dstringt, std::pair<symbolt const*, java_bytecode_parse_treet::methodt const*>, std::less<dstringt>, std::allocator<std::pair<dstringt const, std::pair<symbolt const*, java_bytecode_parse_treet::methodt const*> > > >&, lazy_methods_modet, bool) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_convert_class.cpp:499:5
    #7 0xa136d8 in java_bytecode_languaget::typecheck(symbol_tablet&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/reuben/development/cbmc/src/java_bytecode/java_bytecode_language.cpp:526:8
    #8 0x19b8325 in language_filest::typecheck(symbol_tablet&) /home/reuben/development/cbmc/src/util/language_file.cpp:223:10
    #9 0x152f0df in language_uit::typecheck() /home/reuben/development/cbmc/src/langapi/language_ui.cpp:159:6

SUMMARY: AddressSanitizer: 11912 byte(s) leaked in 141 allocation(s).
```

**Comment by reuk** [comment]
Slightly more minimal example which still leaks:

```java
package Iterator;

import java.util.Iterator;

class DumbIterator implements Iterator<Object> {
  public boolean hasNext() {
    return true;
  }

  public Object next() {
    return null;
  }
}

public class NoLoop_Pass {
  public static void main(String[] args) {
    DumbIterator iterator = new DumbIterator();
    assert iterator.hasNext();
    iterator.next();
  }
}
```

**Comment by reuk** [comment]
Updated the minimal test case.
